// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ5h3tGA6gVSeLWdxVAAPdfc8UW2GxN-k',
    appId: '1:957001835731:web:9c8a02bbbe3efc855be026',
    messagingSenderId: '957001835731',
    projectId: 'blood-donation-27e22',
    authDomain: 'blood-donation-27e22.firebaseapp.com',
    storageBucket: 'blood-donation-27e22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVW3gRn19pGPo2luqEppVU0veW_eHUdrs',
    appId: '1:957001835731:android:ae76accc26333d3e5be026',
    messagingSenderId: '957001835731',
    projectId: 'blood-donation-27e22',
    storageBucket: 'blood-donation-27e22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltThUvQx62n5tifSpohyuxGt2lf1sw_k',
    appId: '1:957001835731:ios:9c44a04e9ae67ca55be026',
    messagingSenderId: '957001835731',
    projectId: 'blood-donation-27e22',
    storageBucket: 'blood-donation-27e22.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBltThUvQx62n5tifSpohyuxGt2lf1sw_k',
    appId: '1:957001835731:ios:9c44a04e9ae67ca55be026',
    messagingSenderId: '957001835731',
    projectId: 'blood-donation-27e22',
    storageBucket: 'blood-donation-27e22.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ5h3tGA6gVSeLWdxVAAPdfc8UW2GxN-k',
    appId: '1:957001835731:web:11537da7ffed725b5be026',
    messagingSenderId: '957001835731',
    projectId: 'blood-donation-27e22',
    authDomain: 'blood-donation-27e22.firebaseapp.com',
    storageBucket: 'blood-donation-27e22.firebasestorage.app',
  );
}
